name: CI

on:
  push:

jobs:
  test-linux:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        pair:
          - erlang: 24
            rebar3: 3.16.1
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.erlang}}
          rebar3-version: ${{matrix.pair.rebar3}}
      - run: rebar3 version
