name: CI

on:
  push:

jobs:
  test-freebsd:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      - run: qemu --version

  # test-macos:
  #   runs-on: macos-11
  #   steps:
  #     - run: uname -a
  # test-linux:
  #   runs-on: ubuntu-18.04
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       pair:
  #         - erlang: 24
  #           rebar3: 3.16.1
  #   steps:
  #     - uses: erlef/setup-beam@v1
  #       with:
  #         otp-version: ${{matrix.pair.erlang}}
  #         rebar3-version: ${{matrix.pair.rebar3}}
  #     - run: rebar3 version
  # test-windows:
  #   runs-on: windows-2019
  #   steps:
  #     - uses: paulo-ferraz-oliveira/setup-beam@feature/erlang-windows-builds
  #       with:
  #        otp-version: 23
  #        rebar3-version: '3.16.1'
  #     - run: rebar3 version
  #     - run: |
  #         mkdir tmp
  #         cd tmp
  #         curl -LO https://github.com/elixir-lang/elixir/releases/download/v1.12.1/Precompiled.zip
  #         unzip Precompiled.zip
  #         dir
  #     - run: Write-Output "$PWD/tmp/bin" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append
  #     - run: elixir --version
