name: CI

on:
  push:

jobs:
  # test-freebsd:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: sudo apt update && sudo apt install -y qemu-system-x86
  #     - run: qemu-system-x86_64 --version

  freebsd:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0.1.4
      with:
        usesh: true
        prepare: pkg install -y curl
        run: |
          pwd
          ls -lah
          whoami
          env
          freebsd-version

  # test-macos:
  #   runs-on: macos-11
  #   steps:
  #     - run: uname -a
  # test-linux:
  #   runs-on: ubuntu-18.04
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       pair:
  #         - erlang: 24
  #           rebar3: 3.16.1
  #   steps:
  #     - uses: erlef/setup-beam@v1
  #       with:
  #         otp-version: ${{matrix.pair.erlang}}
  #         rebar3-version: ${{matrix.pair.rebar3}}
  #     - run: rebar3 version
  # test-windows:
  #   runs-on: windows-2019
  #   steps:
  #     - uses: paulo-ferraz-oliveira/setup-beam@feature/erlang-windows-builds
  #       with:
  #        otp-version: 23
  #        rebar3-version: '3.16.1'
  #     - run: rebar3 version
  #     - run: |
  #         mkdir tmp
  #         cd tmp
  #         curl -LO https://github.com/elixir-lang/elixir/releases/download/v1.12.1/Precompiled.zip
  #         unzip Precompiled.zip
  #         dir
  #     - run: Write-Output "$PWD/tmp/bin" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append
  #     - run: elixir --version
